<a href="https://colab.research.google.com/github/hadil1999-creator/Small-guided-projects-from-coursera-websites../blob/main/Tockenizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
sentences =[
    'I love my dog',
    'I love my cat',
    'I love my dog!',
    'I love you']

tokenizer = Tokenizer(num_words = 100 )
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print (word_index)

{'i': 1, 'love': 2, 'my': 3, 'dog': 4, 'cat': 5, 'you': 6}


Create Poetry (Generating Text)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
data = "No scars to your beautiful \n wwe are stars and we are beautiful"
corpus = data.lower().split("\n")
tokenizer.fit_on_texts(corpus)
total_words =  len(tokenizer.word_index) + 1

In [ ]:
input_sequences = []
for line in corpus : 
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    n_gram_seq = token_list[:i+1]
    input_sequences.append(n_gram_seq)

In [ ]:
input_sequences[3]

[3, 4, 5, 6, 1]

In [ ]:
max_seq_length = max([len (x) for x in input_sequences])
import numpy as np

input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences,maxlen = max_seq_length, padding ='pre'))

In [ ]:
input_sequences[1]

array([0, 0, 0, 0, 3, 4, 5], dtype=int32)

In [ ]:
xs = input_sequences[:,:-1]
labels = input_sequences[:,-1]

In [ ]:
xs[1]

array([0, 0, 0, 0, 3, 4], dtype=int32)

In [ ]:
labels[1]

5

In [ ]:
ys = tf.keras.utils.to_categorical(labels, num_classes = total_words)

In [ ]:
ys[:,:]

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_seq_length-1))
model.add(Bidirectional(LSTM(150)))
model.add(Dense(total_words, activation='softmax'))
adam = Adam(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
#earlystop = EarlyStopping(monitor='val_loss', min_delta=0, patience=5, verbose=0, mode='auto')
history = model.fit(xs, ys, epochs=100, verbose=1)
#print model.summary()
print(model)

In [ ]:
seed_text = "I've got a bad feeling about this"
next_words = 100
  
for _ in range(next_words):
	token_list = tokenizer.texts_to_sequences([seed_text])[0]
	token_list = pad_sequences([token_list], maxlen=max_seq_length-1, padding='pre')
	predicted = (model.predict(token_list) > 0.5).astype("int32")
	output_word = ""
	for word, index in tokenizer.word_index.items():
		if index == predicted:
			output_word = word
			break
	seed_text += " " + output_word
print(seed_text)

ValueError: ignored

Google colab uknown but important features

In [ ]:
from google.colab import data_table
from vega_datasets import data
cars = data.cars()
cars

Name  Miles_per_Gallon  ...       Year  Origin
0    chevrolet chevelle malibu              18.0  ... 1970-01-01     USA
1            buick skylark 320              15.0  ... 1970-01-01     USA
2           plymouth satellite              18.0  ... 1970-01-01     USA
3                amc rebel sst              16.0  ... 1970-01-01     USA
4                  ford torino              17.0  ... 1970-01-01     USA
..                         ...               ...  ...        ...     ...
401            ford mustang gl              27.0  ... 1982-01-01     USA
402                  vw pickup              44.0  ... 1982-01-01  Europe
403              dodge rampage              32.0  ... 1982-01-01     USA
404                ford ranger              28.0  ... 1982-01-01     USA
405                 chevy s-10              31.0  ... 1982-01-01     USA

[406 rows x 9 columns]

Breast Cancer Diagnosis